# ------------------------------------------------------------------------------------------------
# Package Persone - riscaldamento - Ver. 1.1
# Descrizione: gestione riscaldamento quando qualcuno cura le bambine e noi siamo fuori
# ------------------------------------------------------------------------------------------------
# Autore: Henrik Sozzi
# sito: https://henriksozzi.it
# ------------------------------------------------------------------------------------------------
# CHANGELOG
# Ver. 1.0 - 05/05/2021
#   - Miglioramenti per pubblicazione
# Ver. 1.1 - 10/11/2023
#   - Valutazione stato presenza persone per eccezioni temperatura in mansarda
#   - Rinominati gruppi per maggior chiarezza
# ------------------------------------------------------------------------------------------------
# Distribuito con licenza: CC BY-NC-SA 4.0
# Formato leggibile da un essere umano: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.it
# Formato per gli avvocati: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
# ------------------------------------------------------------------------------------------------
input_boolean:
  parenti_a_casa_da_soli:
    name: Parenti a casa da soli?
    icon: mdi:home-account

automation:
  #Gestione Tado in manuale al ritorno / rientro gruppo parenti
  - id: 1438f4c1-05bb-40e1-a855-6a39ec33050c
    alias: Persone - Logica - Uscita con parenti a casa
    description: All'uscita di casa quando uno o più parenti sono casa
    trigger:
      - entity_id: binary_sensor.utenti_tado_a_casa
        platform: state
        from: "on"
    condition:
      - condition: state
        entity_id: group.relatives
        state: home
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.parenti_a_casa_da_soli

  - id: 0b579bbd-4ac6-45af-9b96-319e98dfcb0a
    alias: Persone - Logica - Parenti escono
    description: Parenti escono con nessuno a casa
    trigger:
      - entity_id: group.relatives
        platform: state
        from: home
    condition:
      - condition: state
        entity_id: binary_sensor.utenti_tado_a_casa
        state: "off"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.parenti_a_casa_da_soli

  - id: 6b646b61-f3b7-4782-a4e1-f1e78243267f
    alias: Persone - Logica - Parenti rientrano
    description: Parenti rientrano a casa con nessuno di noi
    trigger:
      - entity_id: group.relatives
        platform: state
        to: home
    condition:
      - condition: state
        entity_id: binary_sensor.utenti_tado_a_casa
        state: "off"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.parenti_a_casa_da_soli

  - id: abad74dc-b21f-4cde-a732-f173a8e3359f
    alias: Persone - Logica - Rientro con parenti a casa
    description: Qualcuno di noi rientra con parenti a casa
    trigger:
      - entity_id: binary_sensor.utenti_tado_a_casa
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: group.relatives
        state: home
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.parenti_a_casa_da_soli

  # Attivazione/disattivazione modalità riscaldamento al cambio di parenti_a_casa_da_soli,
  # sia manualmente che tramite automazioni
  - id: e63b9cfa-8e9e-420a-936b-7300d31f6efa
    alias: Clima - Azione - Cambio stato parenti a casa da soli
    description: Cambio stato dell'input Parenti a casa da soli
    trigger:
      - platform: state
        entity_id: input_boolean.parenti_a_casa_da_soli
      - platform: homeassistant
        event: start
    action:
      - service: script.imposta_riscaldamento
        data:
          entity: "climate.pian_terreno"
      - service: script.imposta_riscaldamento
        data:
          entity: "climate.cameretta"
      - service: script.imposta_riscaldamento
        data:
          entity: "climate.bagno"

  # Cambio riscaldamento inerente a mansarda
  - id: 7798c699-e3dd-46ed-bd1f-48f064b19cb5
    alias: Clima - Azione - Cambio riscaldamento mansarda
    description: Impostazione riscaldamento su eventi inerenti la mansarda
    trigger:
      - platform: state
        entity_id:
          - device_tracker.hshome
          - binary_sensor.erica_at_home
          - binary_sensor.henrik_at_home
          - binary_sensor.antonella_at_home
        to:
      - platform: homeassistant
        event: start
    action:
      - service: script.imposta_riscaldamento
        data:
          entity: "climate.mansarda"
      - service: script.imposta_riscaldamento
        data:
          entity: "climate.bagno_mansarda"
